services:
  nodejs-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BOOKSHOW_SERVICE
    restart: always
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nodejs-service

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
